apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: local-cluster
  title: OTP RHACM Hub Cluster
  description: OTP RHACM Hub Cluster
spec:
  type: kubernetes-cluster
  lifecycle: production
  owner: janus-authors
  system: janus-idp