apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: local-cluster
  title: OTP RHACM Hub Cluster
  description: OTP RHACM Hub Cluster
  links:
    - url: https://console-openshift-console.apps.homelab.swinney.io/multicloud/home/welcome
      title: RHACM Console
      icon: web
spec:
  type: kubernetes-cluster
  lifecycle: production
  owner: janus-authors
  system: janus-idp